version: "3.7"

services:

  item-app:
    image: ghcr.io/arfaniasra/a433-microservices/item-app:v1
    ports:
      - "80:8080"
    restart: "always"
    depends_on:
      - item-db

  item-db:
    image: mongo:3
    volumes:
      - app-db:/data/db

volumes:
  app-db: